language: php
addons:
  sauce_connect: true
php:
  - 5.3
before_script:
  - python -m SimpleHTTPServer &
  - sleep 5
script:
  - cd tests
  - sh set_composer_commit.sh %{commit}
  - composer install
  - vendor/bin/kmsci -a
