language: php
addons:
  sauce_connect: true
php:
  - 5.3
before_script:
  - python -m SimpleHTTPServer &
  - sleep 5
script:
  - npm install -g casperjs
  - composer install
  - cd tests
  - ../bin/kmsci -a
